### PR TITLE
IMP: Expose new match_ids parameter

### LINKED ISSUE #118: denoise-paired: expose matchIDs parameter
**Improvement Description**
Expose the `matchIDs` argument of the `filterAndTrim()` function

**Current Behavior**
The `matchIDs` argument of the `filterAndTrim()` function is `False` by default.

**Proposed Behavior**
A flag would be added to qiime2 so users could optionally set the `matchIDs` argument of the `filterAndTrim()` to `True`

**Questions**
Should we just change this to `True` by default and not expose the setting?

**References**
User story:
https://forum.qiime2.org/t/mismatched-forwward-and-reverse-sequence-files-sequences-imported-by-casava-1-8-paired-end-demultiplexed-fastq-format/10181/2

### PR DESCRIPTION
**Pull request by Oddant1**
closes #118. This currently adds no new unit tests because honestly I'm not 100% on what this behavior is meant to do (it seems to have something to do with mixed orientation), but it does expose the new parameter. Additionally, I'm not positive that it's actually being sent to R properly (in fact I have a strong suspicion it isn't) because I've never tried to do this before, but it's a start.

### CODE REVIEW

**Comment by ebolyen** [comment]
This PR would need to involve editing the R scripts located in `assets` as well.

**Comment by Oddant1** [comment]
@ebolyen yeah I figured as much, I don't really know how that works, but I can figure it out

**Comment by Oddant1** [comment]
@ebolyen is this the correct modifications of the R script? Seems like all I needed to do was put the arg in a variable then pass it off.

**Comment by thermokarst** [comment]
Hey there @ChrisKeefe, can you please review this PR when you get a chance? Please address any changes you might want made to @ebolyen & I - we are teaming up to run this one across the finish line!

**Comment by ebolyen** [comment]
This is probably best addressed by https://github.com/qiime2/q2-types/issues/207, closing for now.

**Pull request closed without merging**
