### PR TITLE
Update Q2-DADA2 to the new (1.6.0) R package release version

### PR DESCRIPTION
**Pull request by benjjneb**

### CODE REVIEW

**Comment by benjjneb** [comment]
After some trial and error, I realized that you must have both the bioconda AND the conda-forge channels in order to install this recipe, as bioconda doesn't have some of the dependencies built for r3.4.1. But the below does work in a local conda environment:

```
conda config --add channels bioconda
conda config --add channels conda-forge
conda install bioconductor-dada2=1.6.0=r3.4.1_0
```

And the following confirms package version 1.6.0:
```
R -e "library(dada2);packageVersion('dada2')"
```

**Comment by thermokarst** [comment]
Thanks @benjjneb! For this to make it into the 2017.12 release cycle it will need to be merged by 12/19. Let us know if you need any help, otherwise, just drop the 'DO-NOT-MERGE' tag when you are ready for one of us to take a look. Thanks so much!

**Comment by thermokarst** [comment]
Also, I am available to help out with this PR, just ping me wherever is convenient for you, @benjjneb!

**Comment by benjjneb** [comment]
I think this is OK to merge. I tried to recreate the failling test on my machine, but it doesn't fail, and I suspect it may have something to do with the differences in the R environment being used in the tests (i.e. R 3.3.2 and older package versions) and the newer 3.4.1 versions. But once it gets into the CI build environments, it starts to get a little beyond me.

**Comment by thermokarst** [comment]
Thanks @benjjneb --- the travis instances run the latest [q2 environment file](https://github.com/qiime2/environment-files/blob/master/latest/staging/qiime2-latest-conda-linux-64.txt), so when we bump dependency versions we usually wind up with a bit of a chicken-and-egg problem --- travis can't test the latest version, because the latest version hasn't been merged (it is a vicious cycle). 

If this PR is ready for review, one of us will pull it down and test locally, since travis can't really help us right now. Thanks!

**Comment by benjjneb** [comment]
Yes its ready to be reviewed.

**Comment by thermokarst** [comment]
Merging even though travis is failing, because of the [reasons mentioned above](https://github.com/qiime2/q2-dada2/pull/78#issuecomment-352016512). Thanks!

**Pull request merged**
